set(TUNGSTEN_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/..")

file(READ "${TUNGSTEN_ROOT_DIR}/VERSION" TUNGSTEN_VERSION_RAW)
string(STRIP "${TUNGSTEN_VERSION_RAW}" TUNGSTEN_VERSION)
string(REPLACE "." ";" TUNGSTEN_VERSION_LIST ${TUNGSTEN_VERSION})

list(LENGTH TUNGSTEN_VERSION_LIST _ver_len)
if(NOT _ver_len EQUAL 3)
    message(FATAL_ERROR "VERSION file contains unknown format; expected: MAJOR.MINOR.PATCH")
endif()

list(GET TUNGSTEN_VERSION_LIST 0 TUNGSTEN_VERSION_MAJOR)
list(GET TUNGSTEN_VERSION_LIST 1 TUNGSTEN_VERSION_MINOR)
list(GET TUNGSTEN_VERSION_LIST 2 TUNGSTEN_VERSION_PATCH)